# Generated by Django 4.2.6 on 2023-11-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='awards_won',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='info',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='happy_clients',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='info',
            name='hero_image',
            field=models.FileField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='info',
            name='image',
            field=models.FileField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='info',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='linkedin_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='project_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='info',
            name='twitter_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
